services:
  postgres-db:
    image: timescale/timescaledb-ha:pg15-latest
    container_name: traffic_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${LOCAL_DB_USER:-admin}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD:-admin123}
      POSTGRES_DB: ${LOCAL_DB_NAME:-traffic_analytics}
    ports:
      - "${LOCAL_DB_PORT:-5433}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LOCAL_DB_USER:-admin} -d ${LOCAL_DB_NAME:-traffic_analytics}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/confluent-local:7.5.0
    container_name: traffic_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  minio:
    image: minio/minio:latest
    container_name: traffic_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # MinIO S3 API Endpoint
      - "9001:9001"   # MinIO Web Console -> http://localhost:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-admin123}
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
